#!/bin/bash
# Open jira ticket based on current git branch
# Before using it: export JIRA_HOST=jira.host.com

unamestr=`uname`
open=open
if [[ "$unamestr" == 'Linux' ]]; then
  open=xdg-open
fi

if [ -n "$1" ]; then 
    ticket="$1";
else
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  # remove the whitespace
  BRANCH=${BRANCH// /}

  if [[ "$BRANCH" =~ [A-Z]+-([0-9])+ ]]; then
    ticket = $BASH_REMATCH
  else
      echo "No jira ticket found in the branch"
  fi
fi

if [ -n "$ticket" ]; then
  URL="http://$JIRA_HOST/browse/$ticket"
  $open $URL
fi
